name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@v0.11.0
    secrets: inherit
    with:
      run-build: true
      run-unit-tests: false
      run-changesets: true
      publish: ${{ github.event_name == 'workflow_dispatch' }}
      publish-command: |
        npm run release

  check_version_change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for version change
        id: version_check
        run: |
          git fetch origin main
          git diff origin/main -- package.json | grep '"version":' || echo "No version change detected"

      - name: Conditional Release
        if: steps.version_check.outputs.version_changed == 'true'
        run: npm run release
