name: publish

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@v0.11.1
    secrets: inherit
    with:
      run-build: true
      run-unit-tests: false
      run-changesets: true
      publish-command: |
        npm run release
