name: publish

on:
  push:
    branches:
      - main
      - tong/add-changeset-support
  workflow_dispatch:

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@hiep/add-changeset
    secrets: inherit
    with:
      run-build: true
      run-unit-tests: false
      run-changesets: true
      publish: ${{ github.event_name == 'workflow_dispatch' }}
      publish-command: |
        ./bin/ci_validate_version.sh
        npm run release
