name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@v0.11.0
    secrets: inherit
    with:
      run-build: true
      run-unit-tests: false
      run-changesets: true
      publish: ${{ github.event_name == 'workflow_dispatch' }}
      publish-command: |
        npm run release
